version: '3.9' 

services: 
    db1: 
        ports:
            - "33060:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: 12345      
        image: mysql/mysql-server  
        
    grafana:
        image: grafana/grafana:latest 
        ports: 
            - "3000:3000" 
